apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - openshift-gitops-argocd-admin-rolebinding.yaml
  - argocd-extended-clusterrole.yaml
  - argocd-extended-clusterrolebinding.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cluster-argocd-application-controller-admin
    path: openshift-gitops-argocd-admin-rolebinding-patch.yaml