kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: contoso-test-ns
  labels:
    app: contoso
    env: test
    group: namespace
spec:
  destination:
    namespace: contoso-test
    server: https://kubernetes.default.svc
  project: namespaces
  source:
    path: overlays/non-prod/01-namespaces/contoso-test
    repoURL: https://github.com/pittar-sandbox/dotnet-contoso-gitops-admins.git
    targetRevision: 4.7
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy