apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-cicd

bases:
  - ../../../../base/02-rbac/openshift-gitops

resources:
  - namespace.yaml
  - quay-creds-secret-sealedsecret.json
  - github-creds-secret-sealedsecret.json
