apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-argocd-developer-admin-rolebinding.yaml
  - argocd-extended-clusterrole.yaml
  - argocd-extended-clusterrolebinding.yaml
